/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.rdl.impl;

import com.minres.rdl.rdl.DefaultProperyAssignment;
import com.minres.rdl.rdl.RdlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Default Propery Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefaultProperyAssignmentImpl extends PropertyAssignmentImpl implements DefaultProperyAssignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefaultProperyAssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.DEFAULT_PROPERY_ASSIGNMENT;
  }

} //DefaultProperyAssignmentImpl
