/*
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.ide

import com.google.inject.Guice
import com.minres.rdl.RDLRuntimeModule
import com.minres.rdl.RDLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RDLIdeSetup extends RDLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RDLRuntimeModule, new RDLIdeModule))
	}
	
}
