/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.minres.rdl.RDLRuntimeModule;
import com.minres.rdl.RDLStandaloneSetup;
import com.minres.rdl.ide.RDLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RDLWebSetup extends RDLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RDLRuntimeModule _rDLRuntimeModule = new RDLRuntimeModule();
    RDLIdeModule _rDLIdeModule = new RDLIdeModule();
    RDLWebModule _rDLWebModule = new RDLWebModule();
    return Guice.createInjector(Modules2.mixin(_rDLRuntimeModule, _rDLIdeModule, _rDLWebModule));
  }
}
