/*
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RDLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRDLWebModule extends DefaultWebModule {

}
