/**
 * generated by Xtext 2.12.0
 */
package com.minres.rdl.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default Propery Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.minres.rdl.rdl.RdlPackage#getDefaultProperyAssignment()
 * @model
 * @generated
 */
public interface DefaultProperyAssignment extends PropertyAssignment
{
} // DefaultProperyAssignment
