/**
 * generated by Xtext 2.12.0
 */
package com.minres.rdl.rdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Immediate Instantiation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.rdl.rdl.ImmediateInstantiation#isExternal <em>External</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.ImmediateInstantiation#getComponentInstances <em>Component Instances</em>}</li>
 * </ul>
 *
 * @see com.minres.rdl.rdl.RdlPackage#getImmediateInstantiation()
 * @model
 * @generated
 */
public interface ImmediateInstantiation extends EObject
{
  /**
   * Returns the value of the '<em><b>External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>External</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' attribute.
   * @see #setExternal(boolean)
   * @see com.minres.rdl.rdl.RdlPackage#getImmediateInstantiation_External()
   * @model
   * @generated
   */
  boolean isExternal();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.ImmediateInstantiation#isExternal <em>External</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External</em>' attribute.
   * @see #isExternal()
   * @generated
   */
  void setExternal(boolean value);

  /**
   * Returns the value of the '<em><b>Component Instances</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.rdl.rdl.ComponentInstance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Instances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Instances</em>' containment reference list.
   * @see com.minres.rdl.rdl.RdlPackage#getImmediateInstantiation_ComponentInstances()
   * @model containment="true"
   * @generated
   */
  EList<ComponentInstance> getComponentInstances();

} // ImmediateInstantiation
