/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Property Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.rdl.rdl.InstancePropertyRef#getInstance <em>Instance</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.InstancePropertyRef#getPropertyEnum <em>Property Enum</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.InstancePropertyRef#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see com.minres.rdl.rdl.RdlPackage#getInstancePropertyRef()
 * @model
 * @generated
 */
public interface InstancePropertyRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Instance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instance</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instance</em>' containment reference.
   * @see #setInstance(InstanceRef)
   * @see com.minres.rdl.rdl.RdlPackage#getInstancePropertyRef_Instance()
   * @model containment="true"
   * @generated
   */
  InstanceRef getInstance();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.InstancePropertyRef#getInstance <em>Instance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instance</em>' containment reference.
   * @see #getInstance()
   * @generated
   */
  void setInstance(InstanceRef value);

  /**
   * Returns the value of the '<em><b>Property Enum</b></em>' attribute.
   * The literals are from the enumeration {@link com.minres.rdl.rdl.PropertyEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property Enum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Enum</em>' attribute.
   * @see com.minres.rdl.rdl.PropertyEnum
   * @see #setPropertyEnum(PropertyEnum)
   * @see com.minres.rdl.rdl.RdlPackage#getInstancePropertyRef_PropertyEnum()
   * @model
   * @generated
   */
  PropertyEnum getPropertyEnum();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.InstancePropertyRef#getPropertyEnum <em>Property Enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Enum</em>' attribute.
   * @see com.minres.rdl.rdl.PropertyEnum
   * @see #getPropertyEnum()
   * @generated
   */
  void setPropertyEnum(PropertyEnum value);

  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(PropertyDefinition)
   * @see com.minres.rdl.rdl.RdlPackage#getInstancePropertyRef_Property()
   * @model
   * @generated
   */
  PropertyDefinition getProperty();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.InstancePropertyRef#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(PropertyDefinition value);

} // InstancePropertyRef
