/**
 * generated by Xtext 2.12.0
 */
package com.minres.rdl.rdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Named Instantiation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.rdl.rdl.NamedInstantiation#isExternal <em>External</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.NamedInstantiation#isInternal <em>Internal</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.NamedInstantiation#getAlias <em>Alias</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.NamedInstantiation#getComponent <em>Component</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.NamedInstantiation#getComponentInstances <em>Component Instances</em>}</li>
 * </ul>
 *
 * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation()
 * @model
 * @generated
 */
public interface NamedInstantiation extends EObject
{
  /**
   * Returns the value of the '<em><b>External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>External</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' attribute.
   * @see #setExternal(boolean)
   * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation_External()
   * @model
   * @generated
   */
  boolean isExternal();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.NamedInstantiation#isExternal <em>External</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External</em>' attribute.
   * @see #isExternal()
   * @generated
   */
  void setExternal(boolean value);

  /**
   * Returns the value of the '<em><b>Internal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Internal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internal</em>' attribute.
   * @see #setInternal(boolean)
   * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation_Internal()
   * @model
   * @generated
   */
  boolean isInternal();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.NamedInstantiation#isInternal <em>Internal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Internal</em>' attribute.
   * @see #isInternal()
   * @generated
   */
  void setInternal(boolean value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' attribute.
   * @see #setAlias(String)
   * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation_Alias()
   * @model
   * @generated
   */
  String getAlias();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.NamedInstantiation#getAlias <em>Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' attribute.
   * @see #getAlias()
   * @generated
   */
  void setAlias(String value);

  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(ComponentDefinition)
   * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation_Component()
   * @model
   * @generated
   */
  ComponentDefinition getComponent();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.NamedInstantiation#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(ComponentDefinition value);

  /**
   * Returns the value of the '<em><b>Component Instances</b></em>' containment reference list.
   * The list contents are of type {@link com.minres.rdl.rdl.ComponentInstance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Instances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Instances</em>' containment reference list.
   * @see com.minres.rdl.rdl.RdlPackage#getNamedInstantiation_ComponentInstances()
   * @model containment="true"
   * @generated
   */
  EList<ComponentInstance> getComponentInstances();

} // NamedInstantiation
