/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.rdl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Property Enum</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.minres.rdl.rdl.RdlPackage#getPropertyEnum()
 * @model
 * @generated
 */
public enum PropertyEnum implements Enumerator
{
  /**
   * The '<em><b>UNSPECIFIED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNSPECIFIED_VALUE
   * @generated
   * @ordered
   */
  UNSPECIFIED(0, "UNSPECIFIED", "UNSPECIFIED"),

  /**
   * The '<em><b>NAME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAME_VALUE
   * @generated
   * @ordered
   */
  NAME(1, "NAME", "name"),

  /**
   * The '<em><b>DESC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESC_VALUE
   * @generated
   * @ordered
   */
  DESC(2, "DESC", "desc"),

  /**
   * The '<em><b>ARBITER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ARBITER_VALUE
   * @generated
   * @ordered
   */
  ARBITER(3, "ARBITER", "arbiter"),

  /**
   * The '<em><b>RSET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RSET_VALUE
   * @generated
   * @ordered
   */
  RSET(4, "RSET", "rset"),

  /**
   * The '<em><b>RCLR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RCLR_VALUE
   * @generated
   * @ordered
   */
  RCLR(5, "RCLR", "rclr"),

  /**
   * The '<em><b>WOCLR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WOCLR_VALUE
   * @generated
   * @ordered
   */
  WOCLR(6, "WOCLR", "woclr"),

  /**
   * The '<em><b>WOSET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WOSET_VALUE
   * @generated
   * @ordered
   */
  WOSET(7, "WOSET", "woset"),

  /**
   * The '<em><b>WE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WE_VALUE
   * @generated
   * @ordered
   */
  WE(8, "WE", "we"),

  /**
   * The '<em><b>WEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEL_VALUE
   * @generated
   * @ordered
   */
  WEL(9, "WEL", "wel"),

  /**
   * The '<em><b>SWWE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SWWE_VALUE
   * @generated
   * @ordered
   */
  SWWE(10, "SWWE", "swwe"),

  /**
   * The '<em><b>SWWEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SWWEL_VALUE
   * @generated
   * @ordered
   */
  SWWEL(11, "SWWEL", "swwel"),

  /**
   * The '<em><b>HWSET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HWSET_VALUE
   * @generated
   * @ordered
   */
  HWSET(12, "HWSET", "hwset"),

  /**
   * The '<em><b>HWCLR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HWCLR_VALUE
   * @generated
   * @ordered
   */
  HWCLR(13, "HWCLR", "hwclr"),

  /**
   * The '<em><b>SWMOD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SWMOD_VALUE
   * @generated
   * @ordered
   */
  SWMOD(14, "SWMOD", "swmod"),

  /**
   * The '<em><b>SWACC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SWACC_VALUE
   * @generated
   * @ordered
   */
  SWACC(15, "SWACC", "swacc"),

  /**
   * The '<em><b>STICKY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STICKY_VALUE
   * @generated
   * @ordered
   */
  STICKY(16, "STICKY", "sticky"),

  /**
   * The '<em><b>STICKYBIT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STICKYBIT_VALUE
   * @generated
   * @ordered
   */
  STICKYBIT(17, "STICKYBIT", "stickybit"),

  /**
   * The '<em><b>INTR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTR_VALUE
   * @generated
   * @ordered
   */
  INTR(18, "INTR", "intr"),

  /**
   * The '<em><b>ANDED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ANDED_VALUE
   * @generated
   * @ordered
   */
  ANDED(19, "ANDED", "anded"),

  /**
   * The '<em><b>ORED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORED_VALUE
   * @generated
   * @ordered
   */
  ORED(20, "ORED", "ored"),

  /**
   * The '<em><b>XORED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #XORED_VALUE
   * @generated
   * @ordered
   */
  XORED(21, "XORED", "xored"),

  /**
   * The '<em><b>COUNTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COUNTER_VALUE
   * @generated
   * @ordered
   */
  COUNTER(22, "COUNTER", "counter"),

  /**
   * The '<em><b>OVERFLOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OVERFLOW_VALUE
   * @generated
   * @ordered
   */
  OVERFLOW(23, "OVERFLOW", "overflow"),

  /**
   * The '<em><b>SHAREDEXTBUS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHAREDEXTBUS_VALUE
   * @generated
   * @ordered
   */
  SHAREDEXTBUS(24, "SHAREDEXTBUS", "sharedextbus"),

  /**
   * The '<em><b>ERREXTBUS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERREXTBUS_VALUE
   * @generated
   * @ordered
   */
  ERREXTBUS(25, "ERREXTBUS", "errextbus"),

  /**
   * The '<em><b>RESET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RESET_VALUE
   * @generated
   * @ordered
   */
  RESET(26, "RESET", "reset"),

  /**
   * The '<em><b>LITTLEENDIAN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LITTLEENDIAN_VALUE
   * @generated
   * @ordered
   */
  LITTLEENDIAN(27, "LITTLEENDIAN", "littleendian"),

  /**
   * The '<em><b>BIGENDIAN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BIGENDIAN_VALUE
   * @generated
   * @ordered
   */
  BIGENDIAN(28, "BIGENDIAN", "bigendian"),

  /**
   * The '<em><b>RSVDSET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RSVDSET_VALUE
   * @generated
   * @ordered
   */
  RSVDSET(29, "RSVDSET", "rsvdset"),

  /**
   * The '<em><b>RSVDSETX</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RSVDSETX_VALUE
   * @generated
   * @ordered
   */
  RSVDSETX(30, "RSVDSETX", "rsvdsetX"),

  /**
   * The '<em><b>BRIDGE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BRIDGE_VALUE
   * @generated
   * @ordered
   */
  BRIDGE(31, "BRIDGE", "bridge"),

  /**
   * The '<em><b>SHARED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHARED_VALUE
   * @generated
   * @ordered
   */
  SHARED(32, "SHARED", "shared"),

  /**
   * The '<em><b>MSB0</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MSB0_VALUE
   * @generated
   * @ordered
   */
  MSB0(33, "MSB0", "msb0"),

  /**
   * The '<em><b>LSB0</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LSB0_VALUE
   * @generated
   * @ordered
   */
  LSB0(34, "LSB0", "lsb0"),

  /**
   * The '<em><b>SYNC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYNC_VALUE
   * @generated
   * @ordered
   */
  SYNC(35, "SYNC", "sync"),

  /**
   * The '<em><b>ASYNC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYNC_VALUE
   * @generated
   * @ordered
   */
  ASYNC(36, "ASYNC", "async"),

  /**
   * The '<em><b>CPUIF RESET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CPUIF_RESET_VALUE
   * @generated
   * @ordered
   */
  CPUIF_RESET(37, "CPUIF_RESET", "cpuif_reset"),

  /**
   * The '<em><b>FIELD RESET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIELD_RESET_VALUE
   * @generated
   * @ordered
   */
  FIELD_RESET(38, "FIELD_RESET", "field_reset"),

  /**
   * The '<em><b>ACTIVEHIGH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACTIVEHIGH_VALUE
   * @generated
   * @ordered
   */
  ACTIVEHIGH(39, "ACTIVEHIGH", "activehigh"),

  /**
   * The '<em><b>ACTIVELOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACTIVELOW_VALUE
   * @generated
   * @ordered
   */
  ACTIVELOW(40, "ACTIVELOW", "activelow"),

  /**
   * The '<em><b>SINGLEPULSE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SINGLEPULSE_VALUE
   * @generated
   * @ordered
   */
  SINGLEPULSE(41, "SINGLEPULSE", "singlepulse"),

  /**
   * The '<em><b>UNDERFLOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNDERFLOW_VALUE
   * @generated
   * @ordered
   */
  UNDERFLOW(42, "UNDERFLOW", "underflow"),

  /**
   * The '<em><b>INCR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCR_VALUE
   * @generated
   * @ordered
   */
  INCR(43, "INCR", "incr"),

  /**
   * The '<em><b>DECR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECR_VALUE
   * @generated
   * @ordered
   */
  DECR(44, "DECR", "decr"),

  /**
   * The '<em><b>INCRWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCRWIDTH_VALUE
   * @generated
   * @ordered
   */
  INCRWIDTH(45, "INCRWIDTH", "incrwidth"),

  /**
   * The '<em><b>DECRWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRWIDTH_VALUE
   * @generated
   * @ordered
   */
  DECRWIDTH(46, "DECRWIDTH", "decrwidth"),

  /**
   * The '<em><b>INCRVALUE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCRVALUE_VALUE
   * @generated
   * @ordered
   */
  INCRVALUE(47, "INCRVALUE", "incrvalue"),

  /**
   * The '<em><b>DECRVALUE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRVALUE_VALUE
   * @generated
   * @ordered
   */
  DECRVALUE(48, "DECRVALUE", "decrvalue"),

  /**
   * The '<em><b>SATURATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SATURATE_VALUE
   * @generated
   * @ordered
   */
  SATURATE(49, "SATURATE", "saturate"),

  /**
   * The '<em><b>DECRSATURATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRSATURATE_VALUE
   * @generated
   * @ordered
   */
  DECRSATURATE(50, "DECRSATURATE", "decrsaturate"),

  /**
   * The '<em><b>THRESHOLD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THRESHOLD_VALUE
   * @generated
   * @ordered
   */
  THRESHOLD(51, "THRESHOLD", "threshold"),

  /**
   * The '<em><b>DECRTHRESHOLD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRTHRESHOLD_VALUE
   * @generated
   * @ordered
   */
  DECRTHRESHOLD(52, "DECRTHRESHOLD", "decrthreshold"),

  /**
   * The '<em><b>DONTCOMPARE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DONTCOMPARE_VALUE
   * @generated
   * @ordered
   */
  DONTCOMPARE(53, "DONTCOMPARE", "dontcompare"),

  /**
   * The '<em><b>DONTTEST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DONTTEST_VALUE
   * @generated
   * @ordered
   */
  DONTTEST(54, "DONTTEST", "donttest"),

  /**
   * The '<em><b>INTERNAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERNAL_VALUE
   * @generated
   * @ordered
   */
  INTERNAL(55, "INTERNAL", "internal"),

  /**
   * The '<em><b>ALIGNMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ALIGNMENT_VALUE
   * @generated
   * @ordered
   */
  ALIGNMENT(56, "ALIGNMENT", "alignment"),

  /**
   * The '<em><b>REGWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REGWIDTH_VALUE
   * @generated
   * @ordered
   */
  REGWIDTH(57, "REGWIDTH", "regwidth"),

  /**
   * The '<em><b>FIELDWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIELDWIDTH_VALUE
   * @generated
   * @ordered
   */
  FIELDWIDTH(58, "FIELDWIDTH", "fieldwidth"),

  /**
   * The '<em><b>SIGNALWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIGNALWIDTH_VALUE
   * @generated
   * @ordered
   */
  SIGNALWIDTH(59, "SIGNALWIDTH", "signalwidth"),

  /**
   * The '<em><b>ACCESSWIDTH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESSWIDTH_VALUE
   * @generated
   * @ordered
   */
  ACCESSWIDTH(60, "ACCESSWIDTH", "accesswidth"),

  /**
   * The '<em><b>SW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SW_VALUE
   * @generated
   * @ordered
   */
  SW(61, "SW", "sw"),

  /**
   * The '<em><b>HW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HW_VALUE
   * @generated
   * @ordered
   */
  HW(62, "HW", "hw"),

  /**
   * The '<em><b>ADDRESSING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ADDRESSING_VALUE
   * @generated
   * @ordered
   */
  ADDRESSING(63, "ADDRESSING", "addressing"),

  /**
   * The '<em><b>PRECEDENCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRECEDENCE_VALUE
   * @generated
   * @ordered
   */
  PRECEDENCE(64, "PRECEDENCE", "precedence"),

  /**
   * The '<em><b>ENCODE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENCODE_VALUE
   * @generated
   * @ordered
   */
  ENCODE(65, "ENCODE", "encode"),

  /**
   * The '<em><b>RESETSIGNAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RESETSIGNAL_VALUE
   * @generated
   * @ordered
   */
  RESETSIGNAL(66, "RESETSIGNAL", "resetsignal"),

  /**
   * The '<em><b>CLOCK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLOCK_VALUE
   * @generated
   * @ordered
   */
  CLOCK(67, "CLOCK", "clock"),

  /**
   * The '<em><b>MASK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MASK_VALUE
   * @generated
   * @ordered
   */
  MASK(68, "MASK", "mask"),

  /**
   * The '<em><b>ENABLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENABLE_VALUE
   * @generated
   * @ordered
   */
  ENABLE(69, "ENABLE", "enable"),

  /**
   * The '<em><b>HWENABLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HWENABLE_VALUE
   * @generated
   * @ordered
   */
  HWENABLE(70, "HWENABLE", "hwenable"),

  /**
   * The '<em><b>HWMASK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HWMASK_VALUE
   * @generated
   * @ordered
   */
  HWMASK(71, "HWMASK", "hwmask"),

  /**
   * The '<em><b>HALTMASK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HALTMASK_VALUE
   * @generated
   * @ordered
   */
  HALTMASK(72, "HALTMASK", "haltmask"),

  /**
   * The '<em><b>HALTENABLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HALTENABLE_VALUE
   * @generated
   * @ordered
   */
  HALTENABLE(73, "HALTENABLE", "haltenable"),

  /**
   * The '<em><b>HALT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HALT_VALUE
   * @generated
   * @ordered
   */
  HALT(74, "HALT", "halt"),

  /**
   * The '<em><b>NEXT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEXT_VALUE
   * @generated
   * @ordered
   */
  NEXT(75, "NEXT", "next");

  /**
   * The '<em><b>UNSPECIFIED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>UNSPECIFIED</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UNSPECIFIED
   * @model
   * @generated
   * @ordered
   */
  public static final int UNSPECIFIED_VALUE = 0;

  /**
   * The '<em><b>NAME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NAME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NAME
   * @model literal="name"
   * @generated
   * @ordered
   */
  public static final int NAME_VALUE = 1;

  /**
   * The '<em><b>DESC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DESC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DESC
   * @model literal="desc"
   * @generated
   * @ordered
   */
  public static final int DESC_VALUE = 2;

  /**
   * The '<em><b>ARBITER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ARBITER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ARBITER
   * @model literal="arbiter"
   * @generated
   * @ordered
   */
  public static final int ARBITER_VALUE = 3;

  /**
   * The '<em><b>RSET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RSET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RSET
   * @model literal="rset"
   * @generated
   * @ordered
   */
  public static final int RSET_VALUE = 4;

  /**
   * The '<em><b>RCLR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RCLR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RCLR
   * @model literal="rclr"
   * @generated
   * @ordered
   */
  public static final int RCLR_VALUE = 5;

  /**
   * The '<em><b>WOCLR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WOCLR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WOCLR
   * @model literal="woclr"
   * @generated
   * @ordered
   */
  public static final int WOCLR_VALUE = 6;

  /**
   * The '<em><b>WOSET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WOSET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WOSET
   * @model literal="woset"
   * @generated
   * @ordered
   */
  public static final int WOSET_VALUE = 7;

  /**
   * The '<em><b>WE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WE
   * @model literal="we"
   * @generated
   * @ordered
   */
  public static final int WE_VALUE = 8;

  /**
   * The '<em><b>WEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEL
   * @model literal="wel"
   * @generated
   * @ordered
   */
  public static final int WEL_VALUE = 9;

  /**
   * The '<em><b>SWWE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SWWE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SWWE
   * @model literal="swwe"
   * @generated
   * @ordered
   */
  public static final int SWWE_VALUE = 10;

  /**
   * The '<em><b>SWWEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SWWEL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SWWEL
   * @model literal="swwel"
   * @generated
   * @ordered
   */
  public static final int SWWEL_VALUE = 11;

  /**
   * The '<em><b>HWSET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HWSET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HWSET
   * @model literal="hwset"
   * @generated
   * @ordered
   */
  public static final int HWSET_VALUE = 12;

  /**
   * The '<em><b>HWCLR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HWCLR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HWCLR
   * @model literal="hwclr"
   * @generated
   * @ordered
   */
  public static final int HWCLR_VALUE = 13;

  /**
   * The '<em><b>SWMOD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SWMOD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SWMOD
   * @model literal="swmod"
   * @generated
   * @ordered
   */
  public static final int SWMOD_VALUE = 14;

  /**
   * The '<em><b>SWACC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SWACC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SWACC
   * @model literal="swacc"
   * @generated
   * @ordered
   */
  public static final int SWACC_VALUE = 15;

  /**
   * The '<em><b>STICKY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>STICKY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STICKY
   * @model literal="sticky"
   * @generated
   * @ordered
   */
  public static final int STICKY_VALUE = 16;

  /**
   * The '<em><b>STICKYBIT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>STICKYBIT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STICKYBIT
   * @model literal="stickybit"
   * @generated
   * @ordered
   */
  public static final int STICKYBIT_VALUE = 17;

  /**
   * The '<em><b>INTR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INTR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTR
   * @model literal="intr"
   * @generated
   * @ordered
   */
  public static final int INTR_VALUE = 18;

  /**
   * The '<em><b>ANDED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ANDED</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ANDED
   * @model literal="anded"
   * @generated
   * @ordered
   */
  public static final int ANDED_VALUE = 19;

  /**
   * The '<em><b>ORED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ORED</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ORED
   * @model literal="ored"
   * @generated
   * @ordered
   */
  public static final int ORED_VALUE = 20;

  /**
   * The '<em><b>XORED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>XORED</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #XORED
   * @model literal="xored"
   * @generated
   * @ordered
   */
  public static final int XORED_VALUE = 21;

  /**
   * The '<em><b>COUNTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>COUNTER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COUNTER
   * @model literal="counter"
   * @generated
   * @ordered
   */
  public static final int COUNTER_VALUE = 22;

  /**
   * The '<em><b>OVERFLOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OVERFLOW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OVERFLOW
   * @model literal="overflow"
   * @generated
   * @ordered
   */
  public static final int OVERFLOW_VALUE = 23;

  /**
   * The '<em><b>SHAREDEXTBUS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SHAREDEXTBUS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SHAREDEXTBUS
   * @model literal="sharedextbus"
   * @generated
   * @ordered
   */
  public static final int SHAREDEXTBUS_VALUE = 24;

  /**
   * The '<em><b>ERREXTBUS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ERREXTBUS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ERREXTBUS
   * @model literal="errextbus"
   * @generated
   * @ordered
   */
  public static final int ERREXTBUS_VALUE = 25;

  /**
   * The '<em><b>RESET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RESET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RESET
   * @model literal="reset"
   * @generated
   * @ordered
   */
  public static final int RESET_VALUE = 26;

  /**
   * The '<em><b>LITTLEENDIAN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LITTLEENDIAN</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LITTLEENDIAN
   * @model literal="littleendian"
   * @generated
   * @ordered
   */
  public static final int LITTLEENDIAN_VALUE = 27;

  /**
   * The '<em><b>BIGENDIAN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BIGENDIAN</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BIGENDIAN
   * @model literal="bigendian"
   * @generated
   * @ordered
   */
  public static final int BIGENDIAN_VALUE = 28;

  /**
   * The '<em><b>RSVDSET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RSVDSET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RSVDSET
   * @model literal="rsvdset"
   * @generated
   * @ordered
   */
  public static final int RSVDSET_VALUE = 29;

  /**
   * The '<em><b>RSVDSETX</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RSVDSETX</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RSVDSETX
   * @model literal="rsvdsetX"
   * @generated
   * @ordered
   */
  public static final int RSVDSETX_VALUE = 30;

  /**
   * The '<em><b>BRIDGE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BRIDGE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BRIDGE
   * @model literal="bridge"
   * @generated
   * @ordered
   */
  public static final int BRIDGE_VALUE = 31;

  /**
   * The '<em><b>SHARED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SHARED</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SHARED
   * @model literal="shared"
   * @generated
   * @ordered
   */
  public static final int SHARED_VALUE = 32;

  /**
   * The '<em><b>MSB0</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MSB0</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MSB0
   * @model literal="msb0"
   * @generated
   * @ordered
   */
  public static final int MSB0_VALUE = 33;

  /**
   * The '<em><b>LSB0</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LSB0</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LSB0
   * @model literal="lsb0"
   * @generated
   * @ordered
   */
  public static final int LSB0_VALUE = 34;

  /**
   * The '<em><b>SYNC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SYNC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SYNC
   * @model literal="sync"
   * @generated
   * @ordered
   */
  public static final int SYNC_VALUE = 35;

  /**
   * The '<em><b>ASYNC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ASYNC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYNC
   * @model literal="async"
   * @generated
   * @ordered
   */
  public static final int ASYNC_VALUE = 36;

  /**
   * The '<em><b>CPUIF RESET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CPUIF RESET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CPUIF_RESET
   * @model literal="cpuif_reset"
   * @generated
   * @ordered
   */
  public static final int CPUIF_RESET_VALUE = 37;

  /**
   * The '<em><b>FIELD RESET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FIELD RESET</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIELD_RESET
   * @model literal="field_reset"
   * @generated
   * @ordered
   */
  public static final int FIELD_RESET_VALUE = 38;

  /**
   * The '<em><b>ACTIVEHIGH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ACTIVEHIGH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACTIVEHIGH
   * @model literal="activehigh"
   * @generated
   * @ordered
   */
  public static final int ACTIVEHIGH_VALUE = 39;

  /**
   * The '<em><b>ACTIVELOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ACTIVELOW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACTIVELOW
   * @model literal="activelow"
   * @generated
   * @ordered
   */
  public static final int ACTIVELOW_VALUE = 40;

  /**
   * The '<em><b>SINGLEPULSE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SINGLEPULSE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SINGLEPULSE
   * @model literal="singlepulse"
   * @generated
   * @ordered
   */
  public static final int SINGLEPULSE_VALUE = 41;

  /**
   * The '<em><b>UNDERFLOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>UNDERFLOW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UNDERFLOW
   * @model literal="underflow"
   * @generated
   * @ordered
   */
  public static final int UNDERFLOW_VALUE = 42;

  /**
   * The '<em><b>INCR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INCR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INCR
   * @model literal="incr"
   * @generated
   * @ordered
   */
  public static final int INCR_VALUE = 43;

  /**
   * The '<em><b>DECR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECR
   * @model literal="decr"
   * @generated
   * @ordered
   */
  public static final int DECR_VALUE = 44;

  /**
   * The '<em><b>INCRWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INCRWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INCRWIDTH
   * @model literal="incrwidth"
   * @generated
   * @ordered
   */
  public static final int INCRWIDTH_VALUE = 45;

  /**
   * The '<em><b>DECRWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRWIDTH
   * @model literal="decrwidth"
   * @generated
   * @ordered
   */
  public static final int DECRWIDTH_VALUE = 46;

  /**
   * The '<em><b>INCRVALUE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INCRVALUE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INCRVALUE
   * @model literal="incrvalue"
   * @generated
   * @ordered
   */
  public static final int INCRVALUE_VALUE = 47;

  /**
   * The '<em><b>DECRVALUE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRVALUE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRVALUE
   * @model literal="decrvalue"
   * @generated
   * @ordered
   */
  public static final int DECRVALUE_VALUE = 48;

  /**
   * The '<em><b>SATURATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SATURATE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SATURATE
   * @model literal="saturate"
   * @generated
   * @ordered
   */
  public static final int SATURATE_VALUE = 49;

  /**
   * The '<em><b>DECRSATURATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRSATURATE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRSATURATE
   * @model literal="decrsaturate"
   * @generated
   * @ordered
   */
  public static final int DECRSATURATE_VALUE = 50;

  /**
   * The '<em><b>THRESHOLD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>THRESHOLD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #THRESHOLD
   * @model literal="threshold"
   * @generated
   * @ordered
   */
  public static final int THRESHOLD_VALUE = 51;

  /**
   * The '<em><b>DECRTHRESHOLD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRTHRESHOLD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRTHRESHOLD
   * @model literal="decrthreshold"
   * @generated
   * @ordered
   */
  public static final int DECRTHRESHOLD_VALUE = 52;

  /**
   * The '<em><b>DONTCOMPARE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DONTCOMPARE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DONTCOMPARE
   * @model literal="dontcompare"
   * @generated
   * @ordered
   */
  public static final int DONTCOMPARE_VALUE = 53;

  /**
   * The '<em><b>DONTTEST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DONTTEST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DONTTEST
   * @model literal="donttest"
   * @generated
   * @ordered
   */
  public static final int DONTTEST_VALUE = 54;

  /**
   * The '<em><b>INTERNAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INTERNAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTERNAL
   * @model literal="internal"
   * @generated
   * @ordered
   */
  public static final int INTERNAL_VALUE = 55;

  /**
   * The '<em><b>ALIGNMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ALIGNMENT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ALIGNMENT
   * @model literal="alignment"
   * @generated
   * @ordered
   */
  public static final int ALIGNMENT_VALUE = 56;

  /**
   * The '<em><b>REGWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>REGWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REGWIDTH
   * @model literal="regwidth"
   * @generated
   * @ordered
   */
  public static final int REGWIDTH_VALUE = 57;

  /**
   * The '<em><b>FIELDWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FIELDWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIELDWIDTH
   * @model literal="fieldwidth"
   * @generated
   * @ordered
   */
  public static final int FIELDWIDTH_VALUE = 58;

  /**
   * The '<em><b>SIGNALWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SIGNALWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SIGNALWIDTH
   * @model literal="signalwidth"
   * @generated
   * @ordered
   */
  public static final int SIGNALWIDTH_VALUE = 59;

  /**
   * The '<em><b>ACCESSWIDTH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ACCESSWIDTH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCESSWIDTH
   * @model literal="accesswidth"
   * @generated
   * @ordered
   */
  public static final int ACCESSWIDTH_VALUE = 60;

  /**
   * The '<em><b>SW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SW
   * @model literal="sw"
   * @generated
   * @ordered
   */
  public static final int SW_VALUE = 61;

  /**
   * The '<em><b>HW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HW
   * @model literal="hw"
   * @generated
   * @ordered
   */
  public static final int HW_VALUE = 62;

  /**
   * The '<em><b>ADDRESSING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ADDRESSING</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ADDRESSING
   * @model literal="addressing"
   * @generated
   * @ordered
   */
  public static final int ADDRESSING_VALUE = 63;

  /**
   * The '<em><b>PRECEDENCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PRECEDENCE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PRECEDENCE
   * @model literal="precedence"
   * @generated
   * @ordered
   */
  public static final int PRECEDENCE_VALUE = 64;

  /**
   * The '<em><b>ENCODE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENCODE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENCODE
   * @model literal="encode"
   * @generated
   * @ordered
   */
  public static final int ENCODE_VALUE = 65;

  /**
   * The '<em><b>RESETSIGNAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RESETSIGNAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RESETSIGNAL
   * @model literal="resetsignal"
   * @generated
   * @ordered
   */
  public static final int RESETSIGNAL_VALUE = 66;

  /**
   * The '<em><b>CLOCK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CLOCK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CLOCK
   * @model literal="clock"
   * @generated
   * @ordered
   */
  public static final int CLOCK_VALUE = 67;

  /**
   * The '<em><b>MASK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MASK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MASK
   * @model literal="mask"
   * @generated
   * @ordered
   */
  public static final int MASK_VALUE = 68;

  /**
   * The '<em><b>ENABLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENABLE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENABLE
   * @model literal="enable"
   * @generated
   * @ordered
   */
  public static final int ENABLE_VALUE = 69;

  /**
   * The '<em><b>HWENABLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HWENABLE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HWENABLE
   * @model literal="hwenable"
   * @generated
   * @ordered
   */
  public static final int HWENABLE_VALUE = 70;

  /**
   * The '<em><b>HWMASK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HWMASK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HWMASK
   * @model literal="hwmask"
   * @generated
   * @ordered
   */
  public static final int HWMASK_VALUE = 71;

  /**
   * The '<em><b>HALTMASK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HALTMASK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HALTMASK
   * @model literal="haltmask"
   * @generated
   * @ordered
   */
  public static final int HALTMASK_VALUE = 72;

  /**
   * The '<em><b>HALTENABLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HALTENABLE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HALTENABLE
   * @model literal="haltenable"
   * @generated
   * @ordered
   */
  public static final int HALTENABLE_VALUE = 73;

  /**
   * The '<em><b>HALT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HALT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HALT
   * @model literal="halt"
   * @generated
   * @ordered
   */
  public static final int HALT_VALUE = 74;

  /**
   * The '<em><b>NEXT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NEXT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NEXT
   * @model literal="next"
   * @generated
   * @ordered
   */
  public static final int NEXT_VALUE = 75;

  /**
   * An array of all the '<em><b>Property Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final PropertyEnum[] VALUES_ARRAY =
    new PropertyEnum[]
    {
      UNSPECIFIED,
      NAME,
      DESC,
      ARBITER,
      RSET,
      RCLR,
      WOCLR,
      WOSET,
      WE,
      WEL,
      SWWE,
      SWWEL,
      HWSET,
      HWCLR,
      SWMOD,
      SWACC,
      STICKY,
      STICKYBIT,
      INTR,
      ANDED,
      ORED,
      XORED,
      COUNTER,
      OVERFLOW,
      SHAREDEXTBUS,
      ERREXTBUS,
      RESET,
      LITTLEENDIAN,
      BIGENDIAN,
      RSVDSET,
      RSVDSETX,
      BRIDGE,
      SHARED,
      MSB0,
      LSB0,
      SYNC,
      ASYNC,
      CPUIF_RESET,
      FIELD_RESET,
      ACTIVEHIGH,
      ACTIVELOW,
      SINGLEPULSE,
      UNDERFLOW,
      INCR,
      DECR,
      INCRWIDTH,
      DECRWIDTH,
      INCRVALUE,
      DECRVALUE,
      SATURATE,
      DECRSATURATE,
      THRESHOLD,
      DECRTHRESHOLD,
      DONTCOMPARE,
      DONTTEST,
      INTERNAL,
      ALIGNMENT,
      REGWIDTH,
      FIELDWIDTH,
      SIGNALWIDTH,
      ACCESSWIDTH,
      SW,
      HW,
      ADDRESSING,
      PRECEDENCE,
      ENCODE,
      RESETSIGNAL,
      CLOCK,
      MASK,
      ENABLE,
      HWENABLE,
      HWMASK,
      HALTMASK,
      HALTENABLE,
      HALT,
      NEXT,
    };

  /**
   * A public read-only list of all the '<em><b>Property Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<PropertyEnum> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Property Enum</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PropertyEnum get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PropertyEnum result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Property Enum</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PropertyEnum getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PropertyEnum result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Property Enum</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PropertyEnum get(int value)
  {
    switch (value)
    {
      case UNSPECIFIED_VALUE: return UNSPECIFIED;
      case NAME_VALUE: return NAME;
      case DESC_VALUE: return DESC;
      case ARBITER_VALUE: return ARBITER;
      case RSET_VALUE: return RSET;
      case RCLR_VALUE: return RCLR;
      case WOCLR_VALUE: return WOCLR;
      case WOSET_VALUE: return WOSET;
      case WE_VALUE: return WE;
      case WEL_VALUE: return WEL;
      case SWWE_VALUE: return SWWE;
      case SWWEL_VALUE: return SWWEL;
      case HWSET_VALUE: return HWSET;
      case HWCLR_VALUE: return HWCLR;
      case SWMOD_VALUE: return SWMOD;
      case SWACC_VALUE: return SWACC;
      case STICKY_VALUE: return STICKY;
      case STICKYBIT_VALUE: return STICKYBIT;
      case INTR_VALUE: return INTR;
      case ANDED_VALUE: return ANDED;
      case ORED_VALUE: return ORED;
      case XORED_VALUE: return XORED;
      case COUNTER_VALUE: return COUNTER;
      case OVERFLOW_VALUE: return OVERFLOW;
      case SHAREDEXTBUS_VALUE: return SHAREDEXTBUS;
      case ERREXTBUS_VALUE: return ERREXTBUS;
      case RESET_VALUE: return RESET;
      case LITTLEENDIAN_VALUE: return LITTLEENDIAN;
      case BIGENDIAN_VALUE: return BIGENDIAN;
      case RSVDSET_VALUE: return RSVDSET;
      case RSVDSETX_VALUE: return RSVDSETX;
      case BRIDGE_VALUE: return BRIDGE;
      case SHARED_VALUE: return SHARED;
      case MSB0_VALUE: return MSB0;
      case LSB0_VALUE: return LSB0;
      case SYNC_VALUE: return SYNC;
      case ASYNC_VALUE: return ASYNC;
      case CPUIF_RESET_VALUE: return CPUIF_RESET;
      case FIELD_RESET_VALUE: return FIELD_RESET;
      case ACTIVEHIGH_VALUE: return ACTIVEHIGH;
      case ACTIVELOW_VALUE: return ACTIVELOW;
      case SINGLEPULSE_VALUE: return SINGLEPULSE;
      case UNDERFLOW_VALUE: return UNDERFLOW;
      case INCR_VALUE: return INCR;
      case DECR_VALUE: return DECR;
      case INCRWIDTH_VALUE: return INCRWIDTH;
      case DECRWIDTH_VALUE: return DECRWIDTH;
      case INCRVALUE_VALUE: return INCRVALUE;
      case DECRVALUE_VALUE: return DECRVALUE;
      case SATURATE_VALUE: return SATURATE;
      case DECRSATURATE_VALUE: return DECRSATURATE;
      case THRESHOLD_VALUE: return THRESHOLD;
      case DECRTHRESHOLD_VALUE: return DECRTHRESHOLD;
      case DONTCOMPARE_VALUE: return DONTCOMPARE;
      case DONTTEST_VALUE: return DONTTEST;
      case INTERNAL_VALUE: return INTERNAL;
      case ALIGNMENT_VALUE: return ALIGNMENT;
      case REGWIDTH_VALUE: return REGWIDTH;
      case FIELDWIDTH_VALUE: return FIELDWIDTH;
      case SIGNALWIDTH_VALUE: return SIGNALWIDTH;
      case ACCESSWIDTH_VALUE: return ACCESSWIDTH;
      case SW_VALUE: return SW;
      case HW_VALUE: return HW;
      case ADDRESSING_VALUE: return ADDRESSING;
      case PRECEDENCE_VALUE: return PRECEDENCE;
      case ENCODE_VALUE: return ENCODE;
      case RESETSIGNAL_VALUE: return RESETSIGNAL;
      case CLOCK_VALUE: return CLOCK;
      case MASK_VALUE: return MASK;
      case ENABLE_VALUE: return ENABLE;
      case HWENABLE_VALUE: return HWENABLE;
      case HWMASK_VALUE: return HWMASK;
      case HALTMASK_VALUE: return HALTMASK;
      case HALTENABLE_VALUE: return HALTENABLE;
      case HALT_VALUE: return HALT;
      case NEXT_VALUE: return NEXT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private PropertyEnum(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //PropertyEnum
