/**
 * generated by Xtext 2.13.0
 */
package com.minres.rdl.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.minres.rdl.rdl.RdlPackage#getPropertyAssignment()
 * @model
 * @generated
 */
public interface PropertyAssignment extends EObject
{
} // PropertyAssignment
