/**
 * generated by Xtext 2.13.0
 */
package com.minres.rdl.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.minres.rdl.rdl.Range#getLeft <em>Left</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.Range#getRight <em>Right</em>}</li>
 *   <li>{@link com.minres.rdl.rdl.Range#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see com.minres.rdl.rdl.RdlPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(Object)
   * @see com.minres.rdl.rdl.RdlPackage#getRange_Left()
   * @model
   * @generated
   */
  Object getLeft();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.Range#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Object value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(Object)
   * @see com.minres.rdl.rdl.RdlPackage#getRange_Right()
   * @model
   * @generated
   */
  Object getRight();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.Range#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(Object value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(Object)
   * @see com.minres.rdl.rdl.RdlPackage#getRange_Size()
   * @model
   * @generated
   */
  Object getSize();

  /**
   * Sets the value of the '{@link com.minres.rdl.rdl.Range#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(Object value);

} // Range
