/*
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.ui;

import com.google.inject.Injector;
import com.minres.rdl.ui.internal.RdlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RdlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RdlActivator activator = RdlActivator.getInstance();
		return activator != null ? activator.getInjector(RdlActivator.COM_MINRES_RDL_RDL) : null;
	}

}
