/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RDLIdeModule extends AbstractRDLIdeModule {
}
