/**
 * generated by Xtext 2.12.0
 */
package com.minres.rdl.ui.contentassist;

import com.minres.rdl.ui.contentassist.AbstractRDLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RDLProposalProvider extends AbstractRDLProposalProvider {
}
