/*
 * generated by Xtext 2.14.0
 */
package com.minres.rdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RDLStandaloneSetup extends RDLStandaloneSetupGenerated {

	def static void doSetup() {
		new RDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
