/*
 * generated by Xtext 2.13.0
 */
package com.minres.rdl.ui.tests;

import com.google.inject.Injector;
import com.minres.rdl.ui.internal.RdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RdlActivator.getInstance().getInjector("com.minres.rdl.RDL");
	}

}
