/**
 * generated by Xtext 2.14.0
 */
package com.minres.rdl;

import com.minres.rdl.RDLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RDLStandaloneSetup extends RDLStandaloneSetupGenerated {
  public static void doSetup() {
    new RDLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
